<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>RxJS  Demo</title>
</head>
<script src='../lib/rxjs6.3.3.umd.js'></script>
<script>
  const {of, range, interval, empty} = rxjs;
  const {mapTo, startWith, scan, tap, map, take, skip, takeLast, last, merge, concat,
    filter, switchMap, concatAll, takeUntil, catchError} = rxjs.operators;

  console.log('demo1: ');
   // 输入 1, 2, 3, 4, 5
   // 输出 1, 2, 3, error
   of(1, 2, 3, 4, 5).pipe(
     map(n => {
       if (n == 4) {
         throw 'four!';
       }
       return n;
     }),
     catchError(err => of(`error`)),
   )
   .subscribe(x => console.log(x));

   console.log('demo2: ');

   of(1, 2, 3, 4, 5).pipe(
     map(n => {
       if (n === 4) {
         throw 'four!';
       }
       return n;
     }),
     catchError((err, caught) => {
       console.log(err);
       console.log(caught);
     }),
     take(6),
   )
   .subscribe(x => console.log(x));

    console.log('demo3: ');

    of(1, 2, 3, 4, 5).pipe(
      map(n => {
        if (n == 4) {
          throw 'four!';
        }
        return n;
      }),
      // err 就是 throw 的内容
      catchError(err => {
        throw 'error in source. Details: ' + err;
      }),
    )
    .subscribe(
      x => console.log(x),
      err => console.log(err)
    );
    // 1, 2, 3, error in source. Details: four!

</script>
</html>
